### ISSUE TITLE
other: is_a parent of GO:0007210 serotonin receptor signaling pathway too specific?

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12029]
Currently 
GO:0007210 serotonin receptor signaling pathway
def: The series of molecular signals generated as a consequence of a serotonin receptor binding to one of its physiological ligands.
is_a GO:0007186 G-protein coupled receptor signaling pathway,

but:

the 5HT3 serotonin receptors are NOT GPCRs, they are non-selective cation channels which are
capable_of_part_of GO:0098655 cation transmembrane transport
def: A process in which a cation is transported from one side of a membrane to the other by means of some agent such as a transporter or pore.

As there is no common parent for GPCRs and cation channels and their MFs and BPs, should GO:0007210 get a very generic is_a parent? Or should we have two pathway terms for the different serotonin receptor signaling pathway?

There are separate MF terms: 
GO:0005232 serotonin-activated cation-selective channel activity (for the cation channels!)
GO:0004993 serotonin receptor activity (for the GPCRs-type receptors)

Ultimately, I have to create the complex based on MF GO:0005232.

Any thoughts?

Birgit

**Comment by bmeldal** [comment]
PMIDs:
16116092 - evidence for 5HT3A homopentamer and A/B heteropentamer
17392525 - evidence for 5HT3A/B, A/C, A/D and A/E heteropentamers
18761359 & 26238288 - reviews

**Comment by bmeldal** [comment]
Complex created in TG complex-template: 
GO:1904602 serotonin-activated cation-selective channel complex

**Comment by dosumis** [comment]
General issue: ligand-gated ion channel activity is not a subClassOf receptor activity in GO.  So GO may actually be consistent here - but at the expense of being confusing.  Need to bring up general issue with editors - should we make ligated-gated ion channel activity a subclass of transmembrane receptor activity.   Many papers certainly call them receptors.

**Comment by bmeldal** [comment]
I have curated a lot of LGIC now and they are all referred to as receptors - which appears logical for me from a biological point of view: ligand binds, channel changes conformation, transported entity travels through channel, channel closes and entity activates next process. It's different from a pre that facilitates passive transport without the need or a ligand or major conformational changes.

So, yes, I think best to discuss in an Editor's call.

**Comment by ValWood** [comment]
In GO the term receptor  is defined 
"Combining with an extracellular or intracellular messenger to initiate a change in cell activity."

Often receptor is just used to mean 'binding' (I think that is the case for transport channels).
Actually it isn't immediately clear to me why these were excluded, but I think they were for some reason. Does  LGIC fit this def?

Val

**Comment by bmeldal** [comment]
I think, yes, Val. The ligand is the 'messenger' and the change in cell activity is clear, in most cases I'm looking at right now it changes the membrane polarisation which eventually activates or blocks neurotransmitter release at a synapse, usually by activating further, voltage-gated channels.

Acetylcholine receptors are very similar (neuronal nicotinic AchR family released yesterday!), so are GABA-A (also released) and glycine receptors (not started yet).

**Comment by dosumis** [comment]
Fixed.  There is now a general term for serotonin receptor.   Following up small amount of re-annotation needed.

**Comment by bmeldal** [comment]
Hi David, 
I can't find the generic term. Has it not been committed yet? Could you let me know when it has so I can check if the inferences have been implemented for my leaf term (GO:1904602 serotonin-activated cation-selective channel complex)?
Thanks,
Birgit

**Comment by bmeldal** [comment]
David,

I had marked this email for follow-up and just come across it again. I just can't find a generic serotonin receptor complex term. My new term GO:1904602 serotonin-activated cation-selective channel complex is a child of GO:0034703 cation channel complex and GO:0043235 receptor complex.

Birgit

**Comment by bmeldal** [comment]
And GO:0007210 serotonin receptor signaling pathway is still
is_a GO:0007186 G-protein coupled receptor signaling pathway

so still doesn't work for the LGIC-type serotonin receptors that I have curated.

**Comment by dosumis** [comment]
Merged GO:0005232 into  GO:0022850

[Term]
 id: GO:0022850
-name: serotonin-gated cation channel activity
+name: serotonin-gated cation-selective channel activity
 namespace: molecular_function
+alt_id: GO:0005232
 def: "Enables the transmembrane transfer of a cation by a channel that opens when serotonin has been bound by the channel complex or one of its constituent parts." [GOC:mtg_transport, ISBN:0815340729]
+comment: Note that this term represents an activity and not a gene product. Consider also annotating to the molecular function term 'serotonin receptor activity ; GO:0004993'.
+synonym: "5-hydroxytryptamine-gated receptor-channel" NARROW []
+synonym: "serotonin-activated cation-selective channel activity" EXACT []
+synonym: "serotonin-gated cation channel activity" NARROW []
+xref: Reactome:REACT_25246 "The 5-HT3 receptor complex is permeable to Na+,K+, and Ca2+ when it binds serotonin (5-HT), Homo sapiens"
+is_a: GO:0005261 ! cation channel activity
 is_a: GO:0022824 ! transmitter-gated ion channel activity
 relationship: has_input CHEBI:28790 ! serotonin


Added:  
[Term]
+id: GO:0098664
+name: G-protein coupled serotonin receptor signaling pathway
+namespace: biological_process
+def: "The series of molecular signals generated as a consequence of a G-protein coupled  serotonin receptor binding to one of its physiological ligands." [GOC:mah]
+intersection_of: GO:0007165 ! signal transduction
+intersection_of: starts_with GO:0004993 ! G-protein coupled serotonin receptor activity
+created_by: dos
+creation_date: 2016-12-21T12:07:58Z
+
+[Term]
+id: GO:0098665
+name: serotonin receptor complex
+namespace: cellular_component
+def: "A protein complex that is capable of serotonin receptor activity." [GO_REF:0000088, GOC:bhm, GOC:TermGenie, PMID:16116092]
+synonym: "5-HT receptor complex" EXACT []
+synonym: "5-hydroxytryptamine receptor complex" EXACT []
+synonym: "5HT receptor complex" EXACT []
+intersection_of: GO:0032991 ! macromolecular complex
+intersection_of: capable_of GO:0099589 ! serotonin receptor activity
+created_by: dos
+creation_date: 2016-12-21T12:24:56Z
+
+[Term]
+id: GO:0098666
+name: G-protein coupled serotonin receptor complex
+namespace: cellular_component
+def: "A protein complex that is capable of G-protein coupled serotonin receptor activity." [GO_REF:0000088, GOC:bhm, GOC:TermGenie]
+intersection_of: GO:0032991 ! macromolecular complex
+intersection_of: capable_of GO:0004993 ! G-protein coupled serotonin receptor activity
+created_by: dos
+creation_date: 2016-12-21T12:28:12Z

![image](https://cloud.githubusercontent.com/assets/112839/21389885/e3c026a0-c77b-11e6-856e-83cc1dca3afa.png)

![image](https://cloud.githubusercontent.com/assets/112839/21389910/f74dc5ce-c77b-11e6-8c28-69d6759f044b.png)

![image](https://cloud.githubusercontent.com/assets/112839/21389915/01d8d33a-c77c-11e6-8f30-b4513bf453a5.png)

**Comment by bmeldal** [comment]
Thanks for the new parent terms, I will check the ontology again when it trickles through :)

Birgit
