### ISSUE TITLE
uberon_import includes a MIREOTed subset of GO, and this plays havoc with the inference pipeline

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#12843]
uberon_import.obo has things like:

```
[Term]
id: GO:0000271
name: polysaccharide biosynthetic process
is_a: GO:0005976 ! polysaccharide metabolic process
is_a: GO:0009059 ! macromolecule biosynthetic process
is_a: GO:0016051 ! carbohydrate biosynthetic process
```

this is as a result of the fact we don't pull in uberon basic, we get the full axioms in order to get taxon constraints. However, we are obviously pulling in too much here (in this case, uberon/go_import.owl)

This has interesting side effects:

## Loss from inferences file

http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/ontology/editors/go_inferences.obo?r1=37306&r2=37305&pathrev=37306

around 1600 links lost

__THIS HAS NOTHING TO DO WITH @ukemi's EDITS__. It is entirely to do with the links being in the import chain via uberon, and hence no longer inferred.

## reappearance in edit file

Furthermore, when OE "imports" uberon_import, the links have lost their is_inferred tags (uberon/go_import launders these away). This means they get saved back here:

http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/ontology/editors/gene_ontology_write.obo?r1=r37407&r2=37305&pathrev=37305

(__NOTHING TO DO WITH__ @tberardini 's edits)

**Comment by cmungall** [comment]
We should fix this soon. The danger is that some of these links will go stale if axioms or chebi changes

**Comment by paolaroncaglia** [comment]
@ukemi @mcourtot
Should we add this to today's agenda?

**Comment by mcourtot** [comment]
Should the uberon_import.obo just be updated to not include any GO terms? Is GO the only consumer of this file (i.e., this is a change we can safely do without impacting others) or do we need to think about another strategy?

**Comment by dosumis** [comment]
> Should the uberon_import.obo just be updated to not include any GO terms? 

Was about to suggest that myself.  I can't see any reason why import stale GO axioms would ever be a good idea.  There are more subtle tail-eating issues than this one (CL and Uberon are partly structured by GO, which is partly structured by both).  With slight asynchronicity old GO could be structured by an older version of itself without every directly importing stale GO terms and axoims.  But I guess we'll deal with that if/when we hit it.

**Comment by ukemi** [comment]
This has been added to today's agenda. It looks like the release is still failing, but that could be due to the duplicate definitions check. I am not sure what effect the alt identifiers are having. All of the is_a orphans are gone.

**Comment by cmungall** [comment]
> I can't see any reason why import stale GO axioms would ever be a good idea. There are more subtle tail-eating issues than this one (CL and Uberon are partly structured by GO, which is partly structured by both). With slight asynchronicity old GO could be structured by an older version of itself without every directly importing stale GO terms and axoims. But I guess we'll deal with that if/when we hit it.

Of course, this was not intentional, see https://github.com/ontodev/robot/issues/119

**Comment by cmungall** [comment]
>  It looks like the release is still failing, but that could be due to the duplicate definitions check

Correct, this is the cause

**Comment by cmungall** [comment]
Once all open ROBOT PRs are merged, we will make a new Uberon release. I will then remove the these asserted isas from the editors file.

This is not particularly time sensitive. If there is a new CHEBI release and this removes the axioms that entail the asserted is_as the we will have a period with stale axioms. But we are not accruing any technical debt on the editors side.

**Comment by paolaroncaglia** [comment]
Chris wrote on chat during today's ontology call:
"I debugged it, did not solve it yet!
the main point is that it's a problem with uberon_import"

**Comment by dosumis** [comment]
Any idea when this will be fixed?  Some of these axioms are getting in the way of me fixing things.

**Comment by cmungall** [comment]
For now I have added a command to the Makefile to strip out any GO in the uberon import

(r37642)

This was the change to the Makefile. It uses a new owltools command that removes classes from an ID space and any referencing axioms. We use this to purge GO classes from the uberon import. Note in future we need more refined precise excision. For example, we may want to keep Uberon and CL axioms that reference GO classes; we just want to exclude axioms that connect GO classes only as these are the province of GO.

```
 $ svn diff Makefile 
Index: Makefile
===================================================================
--- Makefile    (revision 37525)
+++ Makefile    (working copy)
@@ -146,7 +146,7 @@
 
 UBERON_FILTER_C = $(patsubst %, --remove-import-declaration http://purl.obolibrary.org/obo/uberon/%.owl,$(UBERON_FILTER))
 uberon_filtered.owl: uberon_mirror.owl
-       owltools $<  $(UBERON_FILTER_C) --merge-imports-closure --add-obo-shorthand-to-properties --set-ontology-id $(OBO)/uberon.owl -o $@
+       owltools $<  $(UBERON_FILTER_C) --merge-imports-closure --remove-classes-in-idspace -s GO -d --add-obo-shorthand-to-properties --set-ontology-id $(OBO)/uberon.owl -o $@
 .PRECIOUS: uberon_filtered.owl
 
```
