### ISSUE TITLE
GO:0051090    regulation of DNA-binding transcription factor activity query 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17064]
I'm trying to figure how we would use 

GO:0051090 regulation of DNA-binding transcription factor activity

This is a process term. If something is  regulating a DNA binding transcription factor isn't it signalling?
Of if you regulate the activity of a DNA-binding trancription factor 
 directly this would be a molecular function term?

**Comment by bmeldal** [comment]
16 complexes are annotated with children of this term. They have no MF annotations. In the case of the one I checked (https://www.ebi.ac.uk/complexportal/complex/CPX-56) the evidence comes from an experiment where one of the complex components is mutated which causes an increase in transcription activity (by luciferase assay) (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3852661/, F6d, e) --> the complex is annotated with a neg reg child term.

**Comment by pgaudet** [comment]
Looks like these are readouts of signaling pathways. I would tend to obsolete and suggest reannotation to the pathway or regulation of the pathway. 

@vanaukenk What do you think ?

**Comment by RLovering** [comment]
How will histone/DNA modifying TF cofactors be annotated? To regulation of DNA-binding transcription factor activity or would this be to regulation of DNA-binding, or regulation of transcription?

**Comment by pgaudet** [comment]
I would prefer it if we had 'regulator activity' for all direct regulations of protein activities, so the cofactors would be annotate to 'cofactor activity' or even 'transcription factor regulator activity', and to 'regulation of transcription'.

What do you think ? 

Pascale

**Comment by bmeldal** [comment]
"regulator activity" would be great. I guess we'll have quite a few cases where that "X regulator activity" isn't in the ontology yet.

**Comment by ValWood** [comment]
>How will histone/DNA modifying TF cofactors be annotated? 

As far as I'm aware  these are all "recruitment"
https://github.com/pombase/curation/issues/2117
I would really like a "chromatin adaptor"  to describe this activity
(I was still thinking about it, but I think it solves a lot of other issues to where historically "localization" BP has been used.

**Comment by pgaudet** [comment]
We can certainly create 'chromatin adaptor' as a child of 'molecular adaptor activity'.

**Comment by ValWood** [comment]
So wiill "positive regulation of transcription factor activity" be obsoleted as part of the transcription overhaul.
Most of the annotations are just upstream signalling....kinases etc

**Comment by ValWood** [comment]
the  recruitment" part of this ticket is discussed here:
https://github.com/geneontology/go-ontology/issues/17155

**Comment by ValWood** [comment]
Can we get "chromatin adaptor activity" for this?

I need it for tonnes of papers, including the one I am checking now:
Conserved roles of chromatin remodellers in cohesin loading onto chromatin.
PMID: 32277274


<img width="405" alt="Screen Shot 2020-05-06 at 13 41 18" src="https://user-images.githubusercontent.com/7359272/81178056-890b1b80-8f9f-11ea-999d-97af020a6e33.png">

RSC complex is a chromatin remodeller removing nucleosomes for txn and other  DNA metabolism"
One subunit also  acts as a chromatin adaptor for the Scc2/Scc4 cohesin loader complex

**Comment by pgaudet** [comment]
Hi @ValWood 
Can you provide a definition for NTR chromatin adaptor activity ? 
What is it bridging exactly ? 

For eg the definition of 'protein-membrane adaptir activity' is 
> The binding activity of a molecule that brings together a protein or a protein complex with a membrane, or bringing together two membranes, either via membrane lipid binding or by interacting with a membrane protein, to establish or maintain the localization of the protein, protein complex or organelle.

Thanks, Pascale

**Comment by ValWood** [comment]
The binding activity of a molecule that brings together a protein or a protein complex with a nucleosome, to establish or maintain the chromatin localization of the protein, protein complex.
synonym exact chromatin receptor 
related chromatin recruitment

this should work for everything

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140463
+name: protein-chromatin adaptor activity
+namespace: molecular_function
+def: "The binding activity of a molecule that brings together a protein or a protein complex with a nucleosome, to establish or maintain the chromatin localization of the protein, protein complex." [PMID:32277274]
+synonym: "chromatin adaptor activity" EXACT []
+synonym: "chromatin receptor" EXACT []
+is_a: GO:0030674 ! protein-macromolecule adaptor activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/17064 xsd:anyURI
+created_by: pg
+creation_date: 2020-05-08T12:31:39Z

**Comment by pgaudet** [comment]
@ValWood I did not add the synonym 'chromatin recruitment', since this sounds like a process - I think that adds confusion. And related 'chromatin recruiter' sounded odd. 

Thanks, Pascale

**Comment by ValWood** [comment]
I still think we should add "chromatin recruitment" related, because this activity is usually described as "recruitment" in publications. People will search in it.
It does sound like a process which is who it's related.

RIght I'm done for the day!

**Comment by ValWood** [comment]
Can the primary term name be "chromatin adaptor" because that is the term the community would use
(protein-chromatin adaptor doesn't come up in searches but could be an exact synonym)

**Comment by ValWood** [comment]
snall typo
f the protein, protein complex - > or protein complex

**Comment by pgaudet** [comment]
Fixed typo and term label.

**Comment by ValWood** [comment]
Now that the MF term chromatin adaptor is created 
the outstanding question on this ticket is 

How does 
BP regulation of DNA-binding transcription factor activity
GO:0006355    regulation of transcription, DNA-templated

**Comment by pgaudet** [comment]
GO:0051090 regulation of DNA-binding transcription factor activity
is_a  GO:0006355 regulation of transcription, DNA-templated 

Does that answer the question ?

**Comment by ValWood** [comment]
No,
I would understand if it was an MF and part of the process, but this is a process. I still don't understand how the term would be used  (in preference to a descendant of GO:0140110  
transcription regulator activity), unless  it is a "signalling pathway" in which case
it is still a bit strange...

**Comment by pgaudet** [comment]
This will be obsoleted in #22455
