### ISSUE TITLE
Taxon constraint:  various

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25261]
(these were made by a function prediction predictions I'm checking)

Please provide as much information as you can: 

Only in metazoa

- [x] GO:0001505, regulation of neurotransmitter levels
- [x] GO:0005326, neurotransmitter transmembrane transporter activity
- [x] GO:0010098, suspensor development 
- [x] GO:0001775, cell activation (already has never in pombe)
- [x] GO:0036051, protein localization to trailing edge

Never in fungi? 
- [x] GO:0048863, stem cell differentiation
- [x] GO:0003365, establishment of cell polarity involved in ameboidal cell migration
- [x] GO:0090398, cellular senescence 
- [x] GO:0000365, mRNA trans splicing. via spliceosome 
- [ ] GO:0035196, production of miRNAs involved in gene silencing by miRNA 

only in myxomycetes 74506
- [x] GO:0031154, culmination involved in sorocarp development 
- [x] GO:0099138, altruistic. chimeric sorocarp development
- [x] GO:0031152, aggregation involved in sorocarp development

- [ ] GO:0098727 maintenance of cell number. ?

- [ ] GO:0009372, quorum sensing
- [x] GO:0019270, aerobactin biosynthetic process (only in bacteria)
- [x] GO:0016477, cell migration (never in yeast, I seem to remember some fungi that has a flagellum?) (never in ascomycota)

**Comment by ValWood** [comment]
@pgaudet  @balhoff  I just committed these taxon constraints. What  is the other step that needs to happen?

**Comment by balhoff** [comment]
After your changes are merged, then either wait for the GitHub action to run (once per day), which generates the taxon constraints import, or you can kick it off yourself (I can show you how to do that).

**Comment by pfey03** [comment]
@pgaudet Thanks for removing that taxon constraint. What about the protein localization to uropod? Is there an extra issue?

**Comment by ValWood** [comment]
Ah sorry can we add never in yeast
GO:0036051, protein localization to trailing edge
instead

**Comment by pfey03** [comment]
@pgaudet When will these taxon constrains removals go through? I still get automatic emails from ebi every day about these taxon constrains.

**Comment by pgaudet** [comment]
This week I hope! We finally had a successful snapshot this weekend.
